######################################################################
# Automatically generated by qmake (3.0) Wed Jun 24 15:08:46 2015
######################################################################

TEMPLATE = app
TARGET = simplewindow
QT += widgets
CONFIG += qt
QT += gui
INCLUDEPATH += .
CONFIG += debug

# Input
HEADERS += FramelessHelper.h mainwindow.h simplewindow.h
FORMS += mainwindow.ui
SOURCES += FramelessHelper.cpp main.cpp mainwindow.cpp simplewindow.cpp
